USE [master]
GO

CREATE DATABASE [DockerOnWindows]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DockerOnWindows', FILENAME = N'C:\mssql\DockerOnWindows.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DockerOnWindows_log', FILENAME = N'C:\mssql\DockerOnWindows_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DockerOnWindows] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DockerOnWindows].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DockerOnWindows] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DockerOnWindows] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DockerOnWindows] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DockerOnWindows] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DockerOnWindows] SET ARITHABORT OFF 
GO
ALTER DATABASE [DockerOnWindows] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DockerOnWindows] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DockerOnWindows] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DockerOnWindows] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DockerOnWindows] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DockerOnWindows] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DockerOnWindows] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DockerOnWindows] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DockerOnWindows] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DockerOnWindows] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DockerOnWindows] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DockerOnWindows] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DockerOnWindows] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DockerOnWindows] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DockerOnWindows] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DockerOnWindows] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DockerOnWindows] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DockerOnWindows] SET RECOVERY FULL 
GO
ALTER DATABASE [DockerOnWindows] SET  MULTI_USER 
GO
ALTER DATABASE [DockerOnWindows] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DockerOnWindows] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DockerOnWindows] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DockerOnWindows] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DockerOnWindows] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DockerOnWindows', N'ON'
GO
ALTER DATABASE [DockerOnWindows] SET QUERY_STORE = OFF
GO
USE [DockerOnWindows]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [DockerOnWindows]
GO
/****** Object:  Table [dbo].[Authors]    Script Date: 03/05/2017 08:22:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Authors](
	[AuthorId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[TwitterId] [nvarchar](100) NULL,
	[BlogUrl] [nvarchar](500) NULL,
 CONSTRAINT [PK_Authors] PRIMARY KEY CLUSTERED 
(
	[AuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChapterAuthors]    Script Date: 03/05/2017 08:22:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChapterAuthors](
	[ChapterId] [int] NOT NULL,
	[AuthorId] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Chapters]    Script Date: 03/05/2017 08:22:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Chapters](
	[ChapterId] [int] IDENTITY(1,1) NOT NULL,
	[Number] [int] NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[WordCount] [int] NULL,
	[DeliveryDate] [datetime] NULL,
 CONSTRAINT [PK_Chapters] PRIMARY KEY CLUSTERED 
(
	[ChapterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Authors] ON 
GO
INSERT [dbo].[Authors] ([AuthorId], [Name], [TwitterId], [BlogUrl]) VALUES (2, N'Elton Stoneman', N'@EltonStoneman', N'https://blog.sixeyed.com')
GO
SET IDENTITY_INSERT [dbo].[Authors] OFF
GO
ALTER TABLE [dbo].[ChapterAuthors]  WITH CHECK ADD  CONSTRAINT [FK_ChapterAuthors_Authors] FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Authors] ([AuthorId])
GO
ALTER TABLE [dbo].[ChapterAuthors] CHECK CONSTRAINT [FK_ChapterAuthors_Authors]
GO
ALTER TABLE [dbo].[ChapterAuthors]  WITH CHECK ADD  CONSTRAINT [FK_ChapterAuthors_Chapters] FOREIGN KEY([ChapterId])
REFERENCES [dbo].[Chapters] ([ChapterId])
GO
ALTER TABLE [dbo].[ChapterAuthors] CHECK CONSTRAINT [FK_ChapterAuthors_Chapters]
GO
USE [master]
GO
ALTER DATABASE [DockerOnWindows] SET  READ_WRITE 
GO
