{
 "title": "ch11",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ValuesController_Requests) without(instance, job, method, url)"
    }
   ]
  },
  {
   "title": "Total OK Responses",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ValuesController_Responses{code=\"200\"}) without(instance, job, method, url)"
    }
   ]
  },
  {
   "title": "Responses by Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ValuesController_Responses) without(instance, job, method, url)"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(process_cpu_seconds_total)" }
   ]
  },
  { "title": "Nerd Dinner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "IIS Requests /sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "w3svc_w3wp_requests_per_sec" }
   ]
  },
  {
   "title": "IIS Active Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "w3svc_w3wp_requests_per_sec" }
   ]
  },
  {
   "title": "IIS CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_pct_processor_time" }
   ]
  },
  {
   "title": "File Cache",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 8 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "w3svc_w3wp_current_file_cache_memory_usage"
    }
   ]
  },
  {
   "title": "Max. File Cache",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 8 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "w3svc_w3wp_current_file_cache_memory_usage"
    }
   ]
  }
 ]
}