FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1809
#TODO - should be :2.1-runtime-nanoserver-1809

WORKDIR /dotnetapp
COPY ./src/bin/Debug/netcoreapp2.1/publish .

CMD ["dotnet", "HelloWorld.NetCore.dll"]
